default: &default
  adapter: mysql2
  encoding: utf8
  pool: 10
  username: root
  password: 1
  host: 127.0.0.1
development:
    <<: *default
    database: boxroot
production:
  <<: *default
  database: boxroot
